spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ch1project
    username: root
    password: Placebo4114@@!
  jpa:
    hibernate:
      ddl-auto: create


server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

