spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ch1project
    username: root
    password: Placebo4114@@!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass



server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

