server:
  port: 19092

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ch1project
    username: root
    password: Placebo4114@@!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

